# Site settings

title: Jose Herrera | Software Developer
person_name: Jose Herrera
site_name: joherrer

description: >-
  Website of Jose Herrera, Software Developer specializing in backend development,
  cloud computing, and cybersecurity. Explore projects, technical skills, and
  professional services.

default_og_image: /assets/img/profile/developer-og.jpg
locale: en_US

baseurl: ""
url: "https://joherrer.github.io"

github_username: joherrer

markdown: kramdown

plugins:
  - jekyll-sitemap

exclude:
  - .DS_Store
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

permalink: pretty

collections:
  projects:
    output: true
    permalink: /projects/:name/
